"""empty message

Revision ID: 386ae3ce4cb5
Revises: 
Create Date: 2022-07-07 04:20:30.492236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386ae3ce4cb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_birthday_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_birthday_key', 'users', ['birthday'])
    # ### end Alembic commands ###
